traits = {"ALL NFTs": 
            {"BACKGROUND": {"North": 20, "South": 20, "East": 30, "West": 30},
            "ENERGY": {"White Wonder": 10, "White Fear": 7, "White Anger": 5, "White Focus": 6, "White Vertigo": 3, "Black Focus": 5.5, "Black Anger": 5, "Black Wonder": 6, 
                        "Black Fear": 2.5, "Black Vertigo": 5.5, "White Substance": 5, "Black Substance": 1.5, "White Spreading": 5, "Black Spreading": 4.5, "White Composed": 3.5, 
                        "Black Composed": 1.5, "White Swarming": 6, "Black Swarming": 1.5, "White Drain": 5, "Black Drain": 2.5, "White Prickling": 5.5, "Black Prickling": 3}, 
            "BODY": {"Dark Skin": 25, "Tanned Skin": 25, "Light Skin": 25, "Pale Skin": 25},
            "TATTOO": {"Aura": 35, "Witness": 27, "Protector": 23, "No Tattoo": 15},
            "OUTFIT": {"Grey Serious Shirt With Pattern": 0.25, "Red Serious Shirt": 1.5, "Black Serious Shirt": 1.25, "Black Tactical Jacket": 0.75, "Red Tactical Jacket": 1,
                        "Blue Tactical Jacket": 0.25, "White Pioneer Hoodie With Pattern": 1, "White Pioneer Hoodie": 3, "Beige Pioneer Hoodie": 1, "Black Pioneer Hoodie With Pattern": 0.25,
                        "Black Pioneer Hoodie": 1, "Grey Sturdy Hoodie": 3, "Red Sturdy Hoodie": 1, "Black Sturdy Hoodie": 1, "Grey Worn Tshirt": 3.5, "Red Worn Tshirt": 4, 
                        "Black Worn Tshirt": 2.75, "Black Nomad Gown": 1, "Blue Nomad Gown": 1, "White Nomad Gown": 1, "Red Nomad Gown": 1, "White Navigator Jacket": 3,
                        "Black Navigator Jacket": 3, "Blue Navigator Jacket": 3, "Red Shortsleeve Tshirt": 0.25, "Blue Shortsleeve Tshirt": 1, "White Shortsleeve Tshirt": 1.25,
                        "Grey Shortsleeve Tshirt": 0.75, "Red Ritual Sweater": 1, "Blue Ritual Sweater": 1, "Dark Ritual Sweater": 3, "Black Climber Sweater": 0.25, "White Climber Sweater": 1,
                        "Grey Climber Sweater": 1, "Black Rebozo": 1.75, "White Rebozo": 1.5, "Red Rebozo": 3, "Blue Scout Jacket With Pattern": 3, "Red Scout Jacket": 1.25, 
                        "Beige Scout Jacket": 1, "Dark Scout Jacket" : 1, "Black Puffer Jacket": 1, "Red Puffer Jacket": 0.35, "Grey Puffer Jacket": 1, "Blue Puffer Jacket": 3,
                        "Red Ceremonial Garment": 1, "White Ceremonial Garment": 1, "Black Ceremonial Garment": 0.15, "Grey Regular Tshirt": 3, "Red Regular Tshirt": 3, "Red Worn Jacket": 4.5,
                        "Black Worn Jacket": 3, "Beige Worn Jacket": 2.75, "Blue Astral Sweatshirt": 1, "Black Astral Sweatshirt": 1, "Red Astral Sweatshirt": 0.1, "White Traveller Jacket": 3,
                        "Dark Traveller Jacket": 3, "Grey Traveller Jacket": 2.65, "Naked": 3},
            "GEAR": {"Grey Spaulders": 2, "Beige Spaulders": 2, "Beige Pauldron": 0.75, "Grey Pauldron": 1, "Black Climbing Rope": 2, "Beige Climbing Rope": 2, "Black Compact Backpack": 7, 
                    "Beige Compact Backpack": 6, "Beige Frontpack": 1, "Grey Frontpack": 2, "Red Bumbag": 2, "Grey Bumbag": 2, "Beige Mecanic Pack": 5, "Black Mecanic Pack": 5,
                    "Beige Shoulder Pads": 2, "Black Shoulder Pads": 2, "Grey Comfy Backpack": 1, "Beige Comfy Backpack": 1, "Black Rope Necklace": 2, "Red Rope Necklace": 3,
                    "Black Chain": 2.5, "Grey Chain": 1.75, "Beige Crafty Strap": 2, "White Crafty Strap": 2, "Black Rider Backpack": 1, "Beige Rider Backpack": 0.85, "Black Practical Backpack": 2,
                    "Beige Practical Backpack": 2, "Dark Shoulder Spike": 0.15, "Light Shoulder Spike": 0.75, "Beige Small Backpack": 2, "Black Small Backpack": 2, "Black Chestpiece": 5,
                    "Beige Chestpiece": 5, "Black Rope": 1.5, "Beige Rope": 1.5, "Beige Buckle": 5, "Black Buckle": 5, "Black Pockets": 0.25, "Beige Pockets": 2, "No Gear": 5} 
            },
        "MASKLESS": 
            {"HAIR/HAT": {'Red Band': 1.98, 'White Bun': 0.5, 'Black Bun': 4.21, 'Black Priest Hat': 0.5, 'Red Priest Hat': 2.0, 'Light Helmet': 2.0, 'Dark Helmet': 0.5, 'Black Ponytail': 2.0, 
                          'White Ponytail': 2.0, 'Red Beanie': 4.21, 'Grey Beanie': 2.0, 'Black Spikes': 2.0, 'White Spikes': 2.0, 'Blue Posh Hat': 4.21, 'Red Posh Hat': 4.21, 'Black Grunt Beanie': 0.5, 
                          'Red Grunt Beanie': 2.0, 'Chieftain Hat': 0.5, 'Blue Northener Cap': 4.21, 'Red Northener Cap': 4.21, 'Red Bowl Haircut': 2.0, 'Black Bowl Haircut': 2.0, 'Grey Wild Hair': 2.0, 
                          'Red Wild Hair': 2.0, 'Monk Hair': 2.0, 'White Gunther Hair': 4.21, 'Grey Gunther Hair': 0.5, 'Grey Bob': 0.5, 'Blue Bob': 4.21, 'Beige Bob': 4.21, 'Bald': 4.21, 'Grey Band': 2.0, 
                          'Black Band': 2.0, 'White Band': 4.21, 'War Paint': 2.0, 'Teeth Paint': 0.5, 'Lunar Paint': 4.21, 'Vision Paint': 2.0, 'Black Casual Hair': 2.0, 'White Casual Hair': 2.0, 'Red Casual Hair': 0.5, 
                          'Black Mangaka Hair': 2.0, 'Red Mangaka Hair': 2.0, 'White Mangaka Hair': 0.5, 'Focus Paint': 0.5},
            "EYES": {'Eyes Closed': 3.08, 'Red Round Goggles': 1.0, 'Yellow Round Goggles': 2.0, 'Black Screen Of Insight': 2.0, 'Red Screen Of Insight': 2.0, 'Light Cloth Of Perception': 1.0, 
                    'Dark Cloth Of Perception': 1.0, 'Red Three Eyed Mask': 2.0, 'Beige Cross Of Judgment': 3.08, 'Grey Cross Of Judgment': 2.0, 'Grey Cross Of Faith': 2.0, 
                    'Yellow Cross Of Faith': 3.08, 'Red Mountaineer Goggles': 1.0, 'Grey Mountaineer Goggles': 2.5, 'Red Serious Glasses': 1.5, 'Black Serious Glasses': 3.08, 
                    'Yellow Pathfinder': 1.75, 'Red Pathfinder': 0.75, 'White Desert Goggles': 3.08, 'Yellow Desert Goggles': 2.0, 'Red Triangle Goggles': 2.0, 
                    'White Triangle Goggles': 3.08, 'Black Monolens': 2.0, 'Grey Monolens': 2.0, 'White Spikes': 2.0, 'Black Spikes': 2.0, 'Blue Cool Glasses': 4.07, 
                    'Red Cool Glasses': 3.08, 'Red Piercing Eyes': 1.0, 'White Piercing Eyes': 3.08, 'Grey Tubular Goggles': 2.0, 'Black Tubular Goggles': 1.5, 
                    'Black Chain': 2.0, 'Grey Chain': 0.8, 'Black Strips': 2.0, 'White Strips': 2.0, 'Black Hidden Eyes': 2.0, 'Red Rigid Goggles': 3.08, 'Grey Rigid Goggles': 2.0, 
                    'Red Morphy Glasses': 2.25, 'Black Morphy Glasses': 3.08, 'Grey Visualizer': 2.35, 'Black Visualizer': 2.0, 'Grey True Goggles': 2.0, 'Red True Goggles': 2.0, 
                    'Brown Eyes': 3.08, 'Blind Eyes': 1.65},
            "MOUTH": {'Neutral Mouth': 7.0, 'Dark Howl Mouthpiece': 2.0, 'Light Howl Mouthpiece': 8.0, 'Beige Proper Mouthpiece': 2.0, 'Grey Proper Mouthpiece': 0.5, 'Black Hidden Mouth': 2.0, 
                    'Beige Pocket Breather': 0.35, 'Grey Pocket Breather': 2.0, 'Black Spikes': 2.0, 'White Spikes': 2.0, 'Grin Mouth': 8.0, 'Black Screamer Mouthpiece': 7.5, 
                    'Grey Screamer Mouthpiece': 2.0, 'Grey Horror Mouthpiece': 2.5, 'Mouth Cig': 1.5, 'Mouth Tongue': 0.75, 'Red Demon Mouthpiece': 6.5, 'Grey Demon Mouthpiece': 2.25, 
                    'White Tubular Mouthpiece': 7.0, 'Grey Tubular Mouthpiece': 2.0, 'Black Strips': 2.0, 'White Strips': 2.0, 'Beige Tusks': 0.5, 'Grey Tusks': 0.25, 'Red Predator Mouthpiece': 2.0, 
                    'Grey Predator Mouthpiece': 0.5, 'Red Breathing Nosepiece': 7.5, 'Grey Breathing Nosepiece': 2.0, 'Blue Breathing Mouthpiece': 7.5, 'Red Breathing Mouthpiece': 2.0, 'Black Poly Mouthpiece': 0.5, 
                    'Blue Poly Mouthpiece': 2.0, 'White Poly Mouthpiece': 2.9, 'Black Breathing Mouthpiece': 0.5}
            },
        "MINOR MASK":
            {"BASE": {'Minor Mask': 100},
             "STRAPS": {'Chain Straps': 20, 'Short Straps': 45, 'Rope Straps': 25, 'Long Straps': 10},
             "EARS": {'White Ears': 20, 'Beige Ears': 10, 'Red Handle': 15, 'Grey Handle': 10, 'Sticks': 8, 'Beige Pipes': 22, 'Grey Pipes': 16},
             "MOUTH": {'Bitty Mouth': 4.0, 'Howling Mouth': 8.0, 'Doll Mouth': 8.0, 'Crossed Mouth': 4.0, 'Breathing Mouth': 4.0, 'White Quattro Mouth': 1.0, 'Black Quattro Mouth': 4.0, 
                       'Red Closed Mouth': 8.0, 'Grey Closed Mouth': 8.0, 'Beige Dazed Mouth': 4.0, 'Grey Dazed Mouth': 8.0, 'Red Big Mouth': 4.0, 'Grey Big Mouth': 4.0, 'Black Smiling Beak': 4.0, 
                       'Beige Smiling Beak': 4.0, 'Beige Beak': 4.0, 'Red Beak': 1.0, 'Black Grid': 4.0, 'White Grid': 4.0, 'Beige Laughing Mouth': 4.0, 'White Laughing Mouth': 1.0, 
                       'Grey Screaming Mouth': 4.0, 'Beige Screaming Mouth': 1.0},
             "EYES": {'Square Eyes': 5.0, 'Grey Triangles Eyes': 8.75, 'White Triangle Eyes': 8.0, 'Quirky Eyes': 5.0, 'Red True Eyes Visor': 5.0, 'Grey True Eyes Visor': 1.0, 'Beige Hammer Visor': 0.85, 
                      'Grey Hammer Visor': 5.0, 'White One Eyed Visor': 5.25, 'Red One Eyed Visor': 4.75, 'Red Cubic Visor': 5.25, 'Beige Cubic Visor': 8.5, 'White Cubic Visor': 8.5, 'Red Maze Visor': 5.15, 
                      'Grey Maze Visor': 1.0, 'Grey Dual Visor': 1.0, 'Red Dual Visor': 1.0, 'Red Six Cross': 0.75, 'Beige Six Cross': 1.25, 'White Seven Signs': 1.15, 'Grey Seven Signs': 0.85, 'Grey Big Eyes': 8.5, 
                      'White Big Eyes': 8.5},
             "TOP": {'Four Grey Spikes': 4.0, 'Four White Spikes': 4.0, 'Grey Pipe': 6.0, 'White Pipe': 6.0, 'Red Owl Brows': 4.0, 'Grey Owl Brows': 4.0, 'White Owl Brows': 4.0, 'Brush': 4.0, 'Beige Bull Horns': 1.25, 
                     'Grey Bull Horns': 1.35, 'Five Grey Spikes': 4.0, 'Five White Spikes': 4.0, 'Red Swirling Horns': 0.75, 'Grey Swirling Horns': 1.1, 'Beige Swirling Horns': 1.0, 'Beige Ornament': 6.5, 'Red Ornament': 5.5, 
                     'Red Horns And Bun': 4.0, 'Grey Horns And Bun': 4.0, 'Small Beige Spikes': 6.0, 'Small White Spikes': 6.0, 'Dark Sticks': 4.0, 'Light Sticks': 4.0, 'Four Beige Horns': 0.75, 'Four Red Horns': 0.25, 
                     'Four Grey Horns': 0.5, 'Red Antenna': 4.55, 'White Antenna': 4.5}
            },
        "UNIQUE MASK":
            {"MASK": {'Red Mask Of Deceit': 1.16, 'Grey Mask Of Deceit': 1.16, 'Grey Mask Of The Waking Devil': 1.16, 'Red Mask Of The Waking Devil': 0.5, 'Black Mask Of The Sixth Gate': 0.5, 'White Mask Of The Sixth Gate': 1.16, 
                      'Red Mask Of The Guiding Hawk': 1.16, 'Grey Mask Of The Guiding Hawk': 1.16, 'Red Mask Of The Scorpion': 1.16, 'Blue Mask Of The Scorpion': 1.16, 'Blue Mask Of The Usurper': 0.5, 'Red Mask Of The Usurper': 1.16, 
                      'Red Mask Of False Chaos': 1.16, 'Black Mask Of False Chaos': 0.5, 'Blue Mask Of The Falling Star': 1.16, 'Red Mask Of The Falling Star': 0.5, 'Blue Mask Of The Endless Time': 1.25, 'Grey Mask Of The Endless Time': 0.5, 
                      'Blue Mask Of The High Trees': 1.16, 'Red Mask Of The High Trees': 1.16, 'Blue Mask Of Doubt': 1.16, 'Red Mask Of Doubt': 0.5, 'White Mask Of The Destructor': 1.16, 'Grey Mask Of The Destructor': 1.16, 
                      'Blue Mask Of The Ancestor': 1.16, 'Red Mask Of The Ancestor': 0.5, 'Yellow Mask Of The Frail Balance': 1.16, 'Red Mask Of The Frail Balance': 1.16, 'Blue Mask Of The Twelve Dots': 1.0, 'White Mask Of The Twelve Dots': 1.16, 
                      'Blue Mask Of The Wrong Path': 1.16, 'Red Mask Of The Wrong Path': 1.16, 'Blue Mask Of The Nines': 1.16, 'Red Mask Of The Nines': 0.5, 'Red Mask Of The Raider': 1.16, 'Black Mask Of The Raider': 1.16, 'Black Mask Of The Wolf': 1.16, 
                      'Red Mask Of The Wolf': 1.16, 'Red Mask Of The Conjurer': 1.16, 'Grey Mask Of The Conjurer': 1.16, 'Blue Mask Of The Fifth Vision': 0.5, 'Red Mask Of The Fifth Vision': 0.5, 'Red Mask Of The True Blind': 0.5, 'White Mask Of The True Blind': 0.5, 
                      'Black Mask Of The Marauder': 0.5, 'Red Mask Of The Marauder': 1.16, 'Red Mask Of The Reaper': 1.16, 'Black Mask Of The Reaper': 0.5, 'Blue Mask Of The Misfit': 1.16, 'Red Mask Of The Misfit': 1.16, 'Blue Mask Of The Maze': 1.16, 
                      'Red Mask Of The Maze': 0.5, 'Red Mask Of The Dawn': 1.16, 'Black Mask Of The Dawn': 1.16, 'Red Mask Of The Void': 0.5, 'Yellow Mask Of The Void': 1.16, 'Blue Mask Of The Bewitcher': 0.5, 'Red Mask Of The Bewitcher': 0.5, 'Beige Mask Of Rorschach': 1.16, 
                      'Grey Mask Of Rorschach': 0.5, 'Red Mask Of The Scarab': 1.16, 'Grey Mask Of The Scarab': 1.16, 'Blue Mask Of Wisdom': 1.16, 'Red Mask Of Wisdom': 0.5, 'Red Mask Of The Shadows': 0.5, 'White Mask Of The Shadows': 0.5, 'Grey Mask Of The Silence': 1.16, 
                      'Red Mask Of The Silence': 1.16, 'Grey Mask Of The Merciful': 1.16, 'Red Mask Of The Merciful': 0.5, 'Grey Mask Of The Banned': 1.16, 'Blue Mask Of The Banned': 1.16, 'Grey Mask Of The Speaking Wind': 0.5, 'Red Mask Of The Speaking Wind': 0.5, 
                      'Light Mask Of The Infinite Dusk': 1.16, 'Dark Mask Of The Infinite Dusk': 0.5, 'Blue Mask Of The Kooky': 1.16, 'Red Mask Of The Kooky': 1.16, 'Red Mask Of The Moon': 0.5, 'Blue Mask Of The Moon': 1.16, 'Black Mask Of The Deer': 1.16, 
                      'White Mask Of The Deer': 1.16, 'Blue Mask Of The Deep Valley': 0.5, 'Red Mask Of The Deep Valley': 1.16, 'Blue Mask Of The Wanderer': 1.16, 'Red Mask Of The Wanderer': 1.16, 'White Mask Of The Rising Sun': 1.16, 'Blue Mask Of The Rising Sun': 0.5, 
                      'Blue Mask Of The Reacher': 1.16, 'Beige Mask Of The Reacher': 1.16, 'Black Mask Of The Rufa': 0.5, 'Red Mask Of The Rufa': 0.5, 'Yellow Mask Of The Dreamer': 0.5, 'Red Mask Of The Dreamer': 0.5, 'White Mask Of Death': 0.5, 'Grey Mask Of Death': 0.5, 
                      'Blue Mask Of The Trinity': 0.5, 'Red Mask Of The Trinity': 0.5, 'Red Mask Of The Discordant': 1.16, 'Grey Mask Of The Discordant': 1.16, 'Blue Mask Of The Hunter': 0.5, 'Red Mask Of The Hunter': 0.5, 'Black Mask Of The Seeker': 1.16, 'Red Mask Of The Seeker': 1.16, 
                      'Black Mask Of The Underworld': 0.5, 'Grey Mask Of The Underworld': 0.5, 'Blue Mask Of The Fox': 1.16, 'Red Mask Of The Fox': 1.23, 'Blue Mask Of The Dunes': 1.16, 'Beige Mask Of The Dunes': 1.28}
                
            },
        "BONDED MASK":
            {"BASE": {'Bonded Mask': 100},
            "STRAPS": {'Shackle Straps': 25.0, 'Twine Straps': 25.0, 'Knotted Straps': 35.0, 'Pearls Straps': 15.0},
            "EARS": {'Hooks': 10.0, 'Rounded Ears': 25.0, 'Tufts': 30.0, 'Pierced Ears': 15.0, 'Grips': 20.0},
            "MOUTH": {'Beige Awing Mouth': 4.0, 'Red Awing Mouth': 10.0, 'Scraping Mouth': 10.0, 'Ant Mouth': 15.0, 'Monkey Mouth': 3.0, 'Grey Trinity Mouth': 5.0, 'Red Trinity Mouth': 10.0, 'Beige Stern Mouth': 8.5, 'Red Stern Mouth': 5.0, 'Loop Mouth': 12.5, 'Beige Doubtful Mouth': 3.5, 'Red Doubtful Mouth': 7.5, 'Unreal Mouth': 6.0},
            "EYES": {'Round Eyes': 10.0, 'layered visor': 7.5, 'abstract eyes': 8.0, 'Gazing visor': 4.0, 'Flat Visor': 3.0, 'crossed visor': 15.0, 'focused eye': 5.5, 'superior sign': 13.5, 'narrow eyes': 15.0, 'rimmed visor': 7.5, 'converging sign': 4.0, 'awkward eyes': 7.0},
            "TOP": {'beige feathers': 13.5, 'dark feathers': 7.5, 'Four Rods': 5.0, 'layered brow': 5.0, 'beige hooks': 6.0, 'dark hooks': 4.0, 'superior fur': 3.0, 'red buns': 8.0, 'beige horns and tusks': 12.0, 'Dark horns and tusks': 3.0, 'stoic tail': 15.0, 'Dark lunar ornament': 2.5, 'light lunar ornament': 8.0, 'bullish horns': 7.5}
            }
        }
