link = {"ALL NFTs": 
        {'BACKGROUND': {'South': 'ascended_background_south', 'North': 'ascended_background_north', 'East': 'ascended_background_east', 'West': 'ascended_background_west'},
        'ENERGY': {'White Wonder': 'ascended_white_energy_wonder', 'White Fear': 'ascended_white_energy_fear', 'White Anger': 'ascended_white_energy_anger', 'White Focus': 'ascended_white_energy_focus', 
                   'White Vertigo': 'ascended_white_energy_vertigo', 'Black Focus': 'ascended_black_energy_focus', 'Black Anger': 'ascended_black_energy_anger', 'Black Wonder': 'ascended_black_energy_wonder', 
                   'Black Fear': 'ascended_black_energy_fear', 'Black Vertigo': 'ascended_black_energy_vertigo', 'White Substance': 'ascended_white_energy_substance', 'Black Substance': 'ascended_black_energy_substance', 
                   'White Spreading': 'ascended_white_energy_spreading', 'Black Spreading': 'ascended_black_energy_spreading', 'White Composed': 'ascended_white_energy_composed', 'Black Composed': 'ascended_black_energy_composed', 
                   'White Swarming': 'ascended_white_energy_swarming', 'Black Swarming': 'ascended_black_energy_swarming', 'White Drain': 'ascended_white_energy_drain', 'Black Drain': 'ascended_black_energy_drain', 
                   'White Prickling': 'ascended_white_energy_prickling', 'Black Prickling': 'ascended_black_energy_prickling'},
        
        'BODY': {'Dark Skin': 'ascended_skin_dark', 'Tanned Skin': 'ascended_skin_tanned', 'Light Skin': 'ascended_skin_light', 'Pale Skin': 'ascended_skin_pale'},
        
        'TATTOO': {'Aura': 'ascended_outfit_tattoo_aura', 'Witness': 'ascended_outfit_tattoo_witness', 'Protector': 'ascended_outfit_tattoo_protector', 'No Tattoo': 'NO TATOO'},
        
        'OUTFIT': {'Grey Serious Shirt With Pattern': 'ascended_outfit_serious_shirt_grey_pattern', 'Red Serious Shirt': 'ascended_outfit_serious_shirt_red', 'Black Serious Shirt': 'ascended_outfit_serious_shirt_black', 
                   'Black Tactical Jacket': 'ascended_outfit_tactical_jacket_black', 'Red Tactical Jacket': 'ascended_outfit_tactical_jacket_red', 'Blue Tactical Jacket': 'ascended_outfit_tactical_jacket_blue', 
                   'White Pioneer Hoodie With Pattern': 'ascended_outfit_pioneer_hoodie_white_pattern', 'White Pioneer Hoodie': 'ascended_outfit_pioneer_hoodie_white', 'Beige Pioneer Hoodie': 'ascended_outfit_pioneer_hoodie_beige', 
                   'Black Pioneer Hoodie With Pattern': 'ascended_outfit_pioneer_hoodie_black_pattern', 'Black Pioneer Hoodie': 'ascended_outfit_pioneer_hoodie_black', 'Grey Sturdy Hoodie': 'ascended_outfit_sturdy_hoodie_grey', 
                   'Red Sturdy Hoodie': 'ascended_outfit_sturdy_hoodie_red', 'Black Sturdy Hoodie': 'ascended_outfit_sturdy_hoodie_black', 'Grey Worn Tshirt': 'ascended_outfit_worn_tshirt_grey', 'Red Worn Tshirt': 'ascended_outfit_worn_tshirt_red', 
                   'Black Worn Tshirt': 'ascended_outfit_worn_tshirt_black', 'Black Nomad Gown': 'ascended_outfit_nomad_gown_black', 'Blue Nomad Gown': 'ascended_outfit_nomad_gown_blue', 'White Nomad Gown': 'ascended_outfit_nomad_gown_white', 
                   'Red Nomad Gown': 'ascended_outfit_nomad_gown_red', 'White Navigator Jacket': 'ascended_outfit_navigator_jacket_white', 'Black Navigator Jacket': 'ascended_outfit_navigator_jacket_black', 'Blue Navigator Jacket': 'ascended_outfit_navigator_jacket_blue', 
                   'Red Shortsleeve Tshirt': 'ascended_outfit_shortsleeve_tshirt_red', 'Blue Shortsleeve Tshirt': 'ascended_outfit_shortsleeve_tshirt_blue', 'White Shortsleeve Tshirt': 'ascended_outfit_shortsleeve_tshirt_white', 
                   'Grey Shortsleeve Tshirt': 'ascended_outfit_shortsleeve_tshirt_grey', 'Red Ritual Sweater': 'ascended_outfit_ritual_sweater_red', 'Blue Ritual Sweater': 'ascended_outfit_ritual_sweater_blue', 'Dark Ritual Sweater': 'ascended_outfit_ritual_sweater_dark', 
                   'Black Climber Sweater': 'ascended_outfit_climber_sweater_black', 'White Climber Sweater': 'ascended_outfit_climber_sweater_white', 'Grey Climber Sweater': 'ascended_outfit_climber_sweater_grey', 'Black Rebozo': 'ascended_outfit_rebozo_black', 
                   'White Rebozo': 'ascended_outfit_rebozo_white', 'Red Rebozo': 'ascended_outfit_rebozo_red', 'Blue Scout Jacket With Pattern': 'ascended_outfit_scout_jacket_blue_pattern', 'Red Scout Jacket': 'ascended_outfit_scout_jacket_red', 
                   'Beige Scout Jacket': 'ascended_outfit_scout_jacket_beige', 'Dark Scout Jacket': 'ascended_outfit_scout_jacket_dark', 'Black Puffer Jacket': 'ascended_outfit_puffer_jacket_black', 'Red Puffer Jacket': 'ascended_outfit_puffer_jacket_red', 
                   'Grey Puffer Jacket': 'ascended_outfit_puffer_jacket_grey', 'Blue Puffer Jacket': 'ascended_outfit_puffer_jacket_blue', 'Red Ceremonial Garment': 'ascended_outfit_ceremonial_garment_red', 'White Ceremonial Garment': 'ascended_outfit_ceremonial_garment_white', 
                   'Black Ceremonial Garment': 'ascended_outfit_ceremonial_garment_black', 'Grey Regular Tshirt': 'ascended_outfit_regular_tshirt_grey', 'Red Regular Tshirt': 'ascended_outfit_regular_tshirt_red', 'Red Worn Jacket': 'ascended_outfit_worn_jacket_red', 
                   'Black Worn Jacket': 'ascended_outfit_worn_jacket_black', 'Beige Worn Jacket': 'ascended_outfit_worn_jacket_beige', 'Blue Astral Sweatshirt': 'ascended_outfit_astral_sweatshirt_blue', 'Black Astral Sweatshirt': 'ascended_outfit_astral_sweatshirt_black', 
                   'Red Astral Sweatshirt': 'ascended_outfit_astral_sweatshirt_red', 'White Traveller Jacket': 'ascended_outfit_traveller_jacket_white', 'Dark Traveller Jacket': 'ascended_outfit_traveller_jacket_dark', 'Grey Traveller Jacket': 'ascended_outfit_traveller_jacket_grey', 'Naked': 'no outfit (naked)'},
        
        'GEAR': {'Grey Spaulders': 'ascended_gear_spaulders_grey', 'Beige Spaulders': 'ascended_gear_spaulders_beige', 'Beige Pauldron': 'ascended_gear_pauldron_beige', 'Grey Pauldron': 'ascended_gear_pauldron_grey', 'Black Climbing Rope': 'ascended_gear_climbing_rope_black', 
                 'Beige Climbing Rope': 'ascended_gear_climbing_rope_beige', 'Black Compact Backpack': 'ascended_gear_compact_backpack_black', 'Beige Compact Backpack': 'ascended_gear_compact_backpack_beige', 'Beige Frontpack': 'ascended_gear_frontpack_beige', 'Grey Frontpack': 'ascended_gear_frontpack_grey', 
                 'Red Bumbag': 'ascended_gear_bumbag_red', 'Grey Bumbag': 'ascended_gear_bumbag_grey', 'Beige Mecanic Pack': 'ascended_gear_mecanic_pack_beige', 'Black Mecanic Pack': 'ascended_gear_mecanic_pack_black', 'Beige Shoulder Pads': 'ascended_gear_shoulder_pads_beige', 
                 'Black Shoulder Pads': 'ascended_gear_shoulder_pads_black', 'Grey Comfy Backpack': 'ascended_gear_comfy_backpack_grey', 'Beige Comfy Backpack': 'ascended_gear_comfy_backpack_beige', 'Black Rope Necklace': 'ascended_gear_rope_necklace_black', 'Red Rope Necklace': 'ascended_gear_rope_necklace_red', 
                 'Black Chain': 'ascended_gear_chain_black', 'Grey Chain': 'ascended_gear_chain_grey', 'Beige Crafty Strap': 'ascended_gear_crafty_strap_beige', 'White Crafty Strap': 'ascended_gear_crafty_strap_white', 'Black Rider Backpack': 'ascended_gear_rider_backpack_black', 
                 'Beige Rider Backpack': 'ascended_gear_rider_backpack_beige', 'Black Practical Backpack': 'ascended_gear_practical_backpack_black', 'Beige Practical Backpack': 'ascended_gear_practical_backpack_beige', 'Dark Shoulder Spike': 'ascended_gear_shoulder_spike_dark', 
                 'Light Shoulder Spike': 'ascended_gear_shoulder_spike_light', 'Beige Small Backpack': 'ascended_gear_small_backpack_beige', 'Black Small Backpack': 'ascended_gear_small_backpack_black', 'Black Chestpiece': 'ascended_gear_chestpiece_black', 'Beige Chestpiece': 'ascended_gear_chestpiece_beige', 
                 'Black Rope': 'ascended_gear_rope_black', 'Beige Rope': 'ascended_gear_rope_beige', 'Beige Buckle': 'ascended_gear_buckle_beige', 'Black Buckle': 'ascended_gear_buckle_black', 'Black Pockets': 'ascended_gear_pockets_black', 'Beige Pockets': 'ascended_gear_pockets_beige', 'No Gear': 'no gear'},
        },
        'MASKLESS':
            {'HAIR/HAT': {'Red Band': 'ascended_head_band_red', 'White Bun': 'ascended_head_bun_white', 'Black Bun': 'ascended_head_bun_black', 'Black Priest Hat': 'ascended_head_priest_hat_black', 'Red Priest Hat': 'ascended_head_priest_hat_red', 'Light Helmet': 'ascended_head_helmet_light', 
                          'Dark Helmet': 'ascended_head_helmet_dark', 'Black Ponytail': 'ascended_head_ponytail_black', 'White Ponytail': 'ascended_head_ponytail_white', 'Red Beanie': 'ascended_head_beanie_red', 'Grey Beanie': 'ascended_head_beanie_grey', 'Black Spikes': 'ascended_head_spikes_black', 
                          'White Spikes': 'ascended_head_spikes_white', 'Blue Posh Hat': 'ascended_head_posh_hat_blue', 'Red Posh Hat': 'ascended_head_posh_hat_red', 'Black Grunt Beanie': 'ascended_head_grunt_beanie_black', 'Red Grunt Beanie': 'ascended_head_grunt_beanie_red', 'Chieftain Hat': 'ascended_head_chieftain_hat', 
                          'Blue Northener Cap': 'ascended_head_northener_cap_blue', 'Red Northener Cap': 'ascended_head_northener_cap_red', 'Red Bowl Haircut': 'ascended_head_bowl_hair_red', 'Black Bowl Haircut': 'ascended_head_bowl_hair_black', 'Grey Wild Hair': 'ascended_head_wild_hair_grey', 'Red Wild Hair': 'ascended_head_wild_hair_red', 
                          'Monk Hair': 'ascended_head_monk_hair', 'White Gunther Hair': 'ascended_head_gunther_hair_white', 'Grey Gunther Hair': 'ascended_head_gunther_hair_grey', 'Grey Bob': 'ascended_head_bob_grey', 'Blue Bob': 'ascended_head_bob_blue', 'Beige Bob': 'ascended_head_bob_beige', 'Bald': 'nothing (bald)', 
                          'Grey Band': 'ascended_head_band_grey', 'Black Band': 'ascended_head_band_black', 'White Band': 'ascended_head_band_white', 'War Paint': 'ascended_head_war_paint', 'Teeth Paint': 'ascended_head_teeth_paint', 'Lunar Paint': 'ascended_head_lunar_paint', 'Vision Paint': 'ascended_head_vision_paint',
                          'Black Casual Hair': 'ascended_head_casual_hair_black', 'White Casual Hair': 'ascended_head_casual_hair_white', 'Red Casual Hair': 'ascended_head_casual_hair_red', 'Black Mangaka Hair': 'ascended_head_mangaka_black', 'Red Mangaka Hair': 'ascended_head_mangaka_red', 'White Mangaka Hair': 'ascended_head_mangaka_white', 'Focus Paint': 'ascended_head_focus_paint',},
             
            'MOUTH': {'Neutral Mouth': 'ascended_mouth_neutral', 'Dark Howl Mouthpiece': 'ascended_mouth_howl_mouthpiece_dark', 'Light Howl Mouthpiece': 'ascended_mouth_howl_mouthpiece_light', 'Beige Proper Mouthpiece': 'ascended_mouth_proper_mouthpiece_beige', 'Grey Proper Mouthpiece': 'ascended_mouth_proper_mouthpiece_grey', 'Black Hidden Mouth': 'ascended_mouth_hidden_black', 
                      'Beige Pocket Breather': 'ascended_mouth_pocket_breather_beige', 'Grey Pocket Breather': 'ascended_mouth_pocket_breather_grey', 'Black Spikes': 'ascended_mouth_spikes_black', 'White Spikes': 'ascended_mouth_spikes_white', 'Grin Mouth': 'ascended_mouth_grin', 'Black Screamer Mouthpiece': 'ascended_mouth_screamer_mouthpiece_black', 
                      'Grey Screamer Mouthpiece': 'ascended_mouth_screamer_mouthpiece_grey', 'Grey Horror Mouthpiece': 'ascended_mouth_horror_mouthpiece_grey', 'Mouth Cig': 'ascended_mouth_cig', 'Mouth Tongue': 'ascended_mouth_tongue', 'Red Demon Mouthpiece': 'ascended_mouth_demon_mouthpiece_red', 'Grey Demon Mouthpiece': 'ascended_mouth_demon_mouthpiece_grey', 
                      'White Tubular Mouthpiece': 'ascended_mouth_tubular_mouthpiece_white', 'Grey Tubular Mouthpiece': 'ascended_mouth_tubular_mouthpiece_grey', 'Black Strips': 'ascended_mouth_strips_black', 'White Strips': 'ascended_mouth_strips_white', 'Beige Tusks': 'ascended_mouth_tusks_beige', 'Grey Tusks': 'ascended_mouth_tusks_grey', 
                      'Red Predator Mouthpiece': 'ascended_mouth_predator_mouthpiece_red', 'Grey Predator Mouthpiece': 'ascended_mouth_predator_mouthpiece_grey', 'Red Breathing Nosepiece': 'ascended_mouth_breathing_nosepiece_red', 'Grey Breathing Nosepiece': 'ascended_mouth_breathing_nosepiece_grey', 'Blue Breathing Mouthpiece': 'ascended_mouth_breathing_mouthpiece_blue', 
                      'Red Breathing Mouthpiece': 'ascended_mouth_breathing_mouthpiece_red', 'Black Poly Mouthpiece': 'ascended_mouth_poly_mouthpiece_black', 'Blue Poly Mouthpiece': 'ascended_mouth_poly_mouthpiece_blue', 'White Poly Mouthpiece': 'ascended_mouth_poly_mouthpiece_white', 'Black Breathing Mouthpiece': 'ascended_mouth_breathing_mouthpiece_black'},
            
            'EYES': {'Eyes Closed': 'ascended_eyes_closed', 'Red Round Goggles': 'ascended_eyes_round_goggles_red', 'Yellow Round Goggles': 'ascended_eyes_round_goggles_yellow', 'Black Screen Of Insight': 'ascended_eyes_screen_of_insight_black', 'Red Screen Of Insight': 'ascended_eyes_screen_of_insight_red', 'Light Cloth Of Perception': 'ascended_eyes_cloth_of_perception_light', 
                     'Dark Cloth Of Perception': 'ascended_eyes_cloth_of_perception_dark', 'Red Three Eyed Mask': 'ascended_eyes_three_eyed_mask_red', 'Beige Cross Of Judgment': 'ascended_eyes_cross_of_judgment_beige', 'Grey Cross Of Judgment': 'ascended_eyes_cross_of_judgment_grey', 'Grey Cross Of Faith': 'ascended_eyes_cross_of_faith_grey', 'Yellow Cross Of Faith': 'ascended_eyes_cross_of_faith_yellow', 
                     'Red Mountaineer Goggles': 'ascended_eyes_mountaineer_goggles_red', 'Grey Mountaineer Goggles': 'ascended_eyes_mountaineer_goggles_grey', 'Red Serious Glasses': 'ascended_eyes_serious_glasses_red', 'Black Serious Glasses': 'ascended_eyes_serious_glasses_black', 'Yellow Pathfinder': 'ascended_eyes_pathfinder_yellow', 'Red Pathfinder': 'ascended_eyes_pathfinder_red', 
                     'White Desert Goggles': 'ascended_eyes_desert_goggles_white', 'Yellow Desert Goggles': 'ascended_eyes_desert_goggles_yellow', 'Red Triangle Goggles': 'ascended_eyes_triangle_goggles_red', 'White Triangle Goggles': 'ascended_eyes_triangle_goggles_white', 'Black Monolens': 'ascended_eyes_monolens_black', 'Grey Monolens': 'ascended_eyes_monolens_grey', 'White Spikes': 'ascended_eyes_spikes_white', 
                     'Black Spikes': 'ascended_eyes_spikes_black', 'Blue Cool Glasses': 'ascended_eyes_cool_glasses_blue', 'Red Cool Glasses': 'ascended_eyes_cool_glasses_red', 'Red Piercing Eyes': 'ascended_eyes_piercing_eyes_red', 'White Piercing Eyes': 'ascended_eyes_piercing_eyes_white', 'Grey Tubular Goggles': 'ascended_eyes_tubular_goggles_grey', 'Black Tubular Goggles': 'ascended_eyes_tubular_goggles_black', 
                     'Black Chain': 'ascended_eyes_chain_black', 'Grey Chain': 'ascended_eyes_chain_grey', 'Black Strips': 'ascended_eyes_strips_black', 'White Strips': 'ascended_eyes_strips_white', 'Black Hidden Eyes': 'ascended_eyes_hidden_black', 'Red Rigid Goggles': 'ascended_eyes_rigid_goggles_red', 'Grey Rigid Goggles': 'ascended_eyes_rigid_goggles_grey', 'Red Morphy Glasses': 'ascended_eyes_morphy_glasses_red', 
                     'Black Morphy Glasses': 'ascended_eyes_morphy_glasses_black', 'Grey Visualizer': 'ascended_eyes_visualizer_grey', 'Black Visualizer': 'ascended_eyes_visualizer_black', 'Grey True Goggles': 'ascended_eyes_true_goggles_grey', 'Red True Goggles': 'ascended_eyes_true_goggles_red', 'Brown Eyes': 'ascended_eyes_brown', 'Blind Eyes': 'ascended_eyes_blind'},
            
            },
        'MINOR MASK':
            {'BASE': {'Minor Mask': 'ascended_minor_mask_base'},
             
             'STRAPS': {'Chain Straps': 'ascended_minor_mask_chain_straps', 'Short Straps': 'ascended_minor_mask_short_straps', 'Rope Straps': 'ascended_minor_mask_rope_straps', 'Long Straps': 'ascended_minor_mask_long_straps'},
             
             'EARS': {'White Ears': 'ascended_minor_mask_ears_white', 'Beige Ears': 'ascended_minor_mask_ears_handle_grey', 'Red Handle': 'ascended_minor_mask_ears_handle_red', 'Grey Handle': 'ascended_minor_mask_ears_handle_grey', 'Sticks': 'ascended_minor_mask_ears_sticks', 'Beige Pipes': 'ascended_minor_mask_ears_pipes_beige', 'Grey Pipes': 'ascended_minor_mask_ears_pipes_grey'},
             
             'MOUTH': {'Bitty Mouth': 'ascended_minor_mask_bitty_mouth', 'Howling Mouth': 'ascended_minor_mask_howling_mouth', 'Doll Mouth': 'ascended_minor_mask_doll_mouth', 'Crossed Mouth': 'ascended_minor_mask_crossed_mouth', 'Breathing Mouth': 'ascended_minor_mask_breathing_mouth', 'White Quattro Mouth': 'ascended_minor_mask_quattro_mouth_white', 'Black Quattro Mouth': 'ascended_minor_mask_quattro_mouth_black', 
                       'Red Closed Mouth': 'ascended_minor_mask_closed_mouth_red', 'Grey Closed Mouth': 'ascended_minor_mask_closed_mouth_grey', 'Beige Dazed Mouth': 'ascended_minor_mask_dazed_mouth_beige', 'Grey Dazed Mouth': 'ascended_minor_mask_dazed_mouth_grey', 'Red Big Mouth': 'ascended_minor_mask_big_mouth_red', 'Grey Big Mouth': 'ascended_minor_mask_big_mouth_grey', 
                       'Black Smiling Beak': 'ascended_minor_mask_smiling_beak_mouth_black', 'Beige Smiling Beak': 'ascended_minor_mask_smiling_beak_mouth_beige', 'Beige Beak': 'ascended_minor_mask_beak_mouth_beige', 'Red Beak': 'ascended_minor_mask_beak_mouth_red', 'Black Grid': 'ascended_minor_mask_grid_mouth_black', 'White Grid': 'ascended_minor_mask_grid_mouth_white', 
                       'Beige Laughing Mouth': 'ascended_minor_mask_laughing_mouth_beige', 'White Laughing Mouth': 'ascended_minor_mask_laughing_mouth_white', 'Grey Screaming Mouth': 'ascended_minor_mask_screaming_mouth_grey', 'Beige Screaming Mouth': 'ascended_minor_mask_screaming_mouth_beige'},
             
             'EYES': {'Square Eyes': 'ascended_minor_mask_eyes_square_eyes', 'Grey Triangles Eyes': 'ascended_minor_mask_eyes_triangle_eyes_grey', 'White Triangle Eyes': 'ascended_minor_mask_eyes_triangle_eyes_white', 'Quirky Eyes': 'ascended_minor_mask_eyes_quirky_eyes', 'Red True Eyes Visor': 'ascended_minor_mask_eyes_true_eye_visor_red', 'Grey True Eyes Visor': 'ascended_minor_mask_eyes_true_eye_visor_grey', 
                      'Beige Hammer Visor': 'ascended_minor_mask_eyes_hammer_visor_beige', 'Grey Hammer Visor': 'ascended_minor_mask_eyes_hammer_visor_grey', 'White One Eyed Visor': 'ascended_minor_mask_eyes_one_eyed_visor_white', 'Red One Eyed Visor': 'ascended_minor_mask_eyes_one_eyed_visor_red', 'Red Cubic Visor': 'ascended_minor_mask_eyes_cubic_visor_red', 'Beige Cubic Visor': 'ascended_minor_mask_eyes_cubic_visor_beige', 
                      'White Cubic Visor': 'ascended_minor_mask_eyes_cubic_visor_white', 'Red Maze Visor': 'ascended_minor_mask_eyes_maze_visor_red', 'Grey Maze Visor': 'ascended_minor_mask_eyes_maze_visor_grey', 'Grey Dual Visor': 'ascended_minor_mask_eyes_dual_visor_grey', 'Red Dual Visor': 'ascended_minor_mask_eyes_dual_visor_red', 'Red Six Cross': 'ascended_minor_mask_eyes_six_cross_red', 'Beige Six Cross': 'ascended_minor_mask_eyes_six_cross_beige', 
                      'White Seven Signs': 'ascended_minor_mask_eyes_seven_signs_white', 'Grey Seven Signs': 'ascended_minor_mask_eyes_seven_signs_grey', 'Grey Big Eyes': 'ascended_minor_mask_eyes_big_eyes_grey', 'White Big Eyes': 'ascended_minor_mask_eyes_big_eyes_white'},
             'TOP': {'Four Grey Spikes': 'ascended_minor_mask_top_four_spikes_grey', 'Four White Spikes': 'ascended_minor_mask_top_four_spikes_white', 'Grey Pipe': 'ascended_minor_mask_top_pipe_grey', 'White Pipe': 'ascended_minor_mask_top_pipe_white', 'Red Owl Brows': 'ascended_minor_mask_top_owl_brows_red', 'Grey Owl Brows': 'ascended_minor_mask_top_owl_brows_grey', 'White Owl Brows': 'ascended_minor_mask_top_owl_brows_white', 
                     'Brush': 'ascended_minor_mask_top_brush', 'Beige Bull Horns': 'ascended_minor_mask_top_bull_horns_beige', 'Grey Bull Horns': 'ascended_minor_mask_top_bull_horns_grey', 'Five Grey Spikes': 'ascended_minor_mask_top_five_spikes_grey', 'Five White Spikes': 'ascended_minor_mask_top_five_spikes_white', 'Red Swirling Horns': 'ascended_minor_mask_top_swirling_horns_red', 'Grey Swirling Horns': 'ascended_minor_mask_top_swirling_horns_grey', 
                     'Beige Swirling Horns': 'ascended_minor_mask_top_swirling_horns_beige', 'Beige Ornament': 'ascended_minor_mask_top_ornament_beige', 'Red Ornament': 'ascended_minor_mask_top_ornament_red', 'Red Horns And Bun': 'ascended_minor_mask_top_horns_and_bun_red', 'Grey Horns And Bun': 'ascended_minor_mask_top_horns_and_bun_grey', 'Small Beige Spikes': 'ascended_minor_mask_top_small_spikes_beige', 'Small White Spikes': 'ascended_minor_mask_top_small_spikes_white', 
                     'Dark Sticks': 'ascended_minor_mask_top_sticks_dark', 'Light Sticks': 'ascended_minor_mask_top_sticks_light', 'Four Beige Horns': 'ascended_minor_mask_top_four_horns_beige', 'Four Red Horns': 'ascended_minor_mask_top_four_horns_red', 'Four Grey Horns': 'ascended_minor_mask_top_four_horns_grey', 'Red Antenna': 'ascended_minor_mask_top_antenna_red', 'White Antenna': 'ascended_minor_mask_top_antenna_white'}
             
            },
        'UNIQUE MASK':
            {'MASK': {'Red Mask Of Deceit': 'ascended_mask_of_deceit_red', 'Grey Mask Of Deceit': 'ascended_mask_of_deceit_grey', 'Grey Mask Of The Waking Devil': 'ascended_mask_of_the_waking_devil_grey', 'Red Mask Of The Waking Devil': 'ascended_mask_of_the_waking_devil_red', 'Black Mask Of The Sixth Gate': 'ascended_mask_of_the_sixth_gate_black', 'White Mask Of The Sixth Gate': 'ascended_mask_of_the_sixth_gate_white', 'Red Mask Of The Guiding Hawk': 'ascended_mask_of_the_guiding_hawk_red', 
                      'Grey Mask Of The Guiding Hawk': 'ascended_mask_of_the_guiding_hawk_grey', 'Red Mask Of The Scorpion': 'ascended_mask_of_the_scorpion_red', 'Blue Mask Of The Scorpion': 'ascended_mask_of_the_scorpion_blue', 'Blue Mask Of The Usurper': 'ascended_mask_of_the_usurper_blue', 'Red Mask Of The Usurper': 'ascended_mask_of_the_usurper_red', 'Red Mask Of False Chaos': 'ascended_mask_of_false_chaos_red', 'Black Mask Of False Chaos': 'ascended_mask_of_false_chaos_black', 
                      'Blue Mask Of The Falling Star': 'ascended_mask_of_the_falling_star_blue', 'Red Mask Of The Falling Star': 'ascended_mask_of_the_falling_star_red', 'Blue Mask Of The Endless Time': 'ascended_mask_of_endless_time_blue', 'Grey Mask Of The Endless Time': 'ascended_mask_of_endless_time_grey', 'Blue Mask Of The High Trees': 'ascended_mask_of_the_high_trees_blue', 'Red Mask Of The High Trees': 'ascended_mask_of_the_high_trees_red', 'Blue Mask Of Doubt': 'ascended_mask_of_doubt_blue', 
                      'Red Mask Of Doubt': 'ascended_mask_of_doubt_red', 'White Mask Of The Destructor': 'ascended_mask_of_the_destructor_white', 'Grey Mask Of The Destructor': 'ascended_mask_of_the_destructor_grey', 'Blue Mask Of The Ancestor': 'ascended_mask_of_the_ancestor_blue', 'Red Mask Of The Ancestor': 'ascended_mask_of_the_ancestor_red', 'Yellow Mask Of The Frail Balance': 'ascended_mask_of_the_frail_balance_yellow', 'Red Mask Of The Frail Balance': 'ascended_mask_of_the_frail_balance_red', 
                      'Blue Mask Of The Twelve Dots': 'ascended_mask_of_the_twelve_dots_blue', 'White Mask Of The Twelve Dots': 'ascended_mask_of_the_twelve_dots_white', 'Blue Mask Of The Wrong Path': 'ascended_mask_of_the_wrong_path_blue', 'Red Mask Of The Wrong Path': 'ascended_mask_of_the_wrong_path_red', 'Blue Mask Of The Nines': 'ascended_mask_of_the_nines_blue', 'Red Mask Of The Nines': 'ascended_mask_of_the_nines_red', 'Red Mask Of The Raider': 'ascended_mask_of_the_raider_red', 
                      'Black Mask Of The Raider': 'ascended_mask_of_the_raider_black', 'Black Mask Of The Wolf': 'ascended_mask_of_the_wolf_black', 'Red Mask Of The Wolf': 'ascended_mask_of_the_wolf_red', 'Red Mask Of The Conjurer': 'ascended_mask_of_the_conjurer_red', 'Grey Mask Of The Conjurer': 'ascended_mask_of_the_conjurer_grey', 'Blue Mask Of The Fifth Vision': 'ascended_mask_of_the_fifth_vision_blue', 'Red Mask Of The Fifth Vision': 'ascended_mask_of_the_fifth_vision_red', 
                      'Red Mask Of The True Blind': 'ascended_mask_of_the_true_blind_red', 'White Mask Of The True Blind': 'ascended_mask_of_the_true_blind_white', 'Black Mask Of The Marauder': 'ascended_mask_of_the_marauder_black', 'Red Mask Of The Marauder': 'ascended_mask_of_the_marauder_red', 'Red Mask Of The Reaper': 'ascended_mask_of_the_reaper_red', 'Black Mask Of The Reaper': 'ascended_mask_of_the_reaper_black', 'Blue Mask Of The Misfit': 'ascended_mask_of_the_misfit_blue', 
                      'Red Mask Of The Misfit': 'ascended_mask_of_the_misfit_red', 'Blue Mask Of The Maze': 'ascended_mask_of_the_maze_blue', 'Red Mask Of The Maze': 'ascended_mask_of_the_maze_red', 'Red Mask Of The Dawn': 'ascended_mask_of_the_dawn_red', 'Black Mask Of The Dawn': 'ascended_mask_of_the_dawn_black', 'Red Mask Of The Void': 'ascended_mask_of_the_void_red', 'Yellow Mask Of The Void': 'ascended_mask_of_the_void_yellow', 'Blue Mask Of The Bewitcher': 'ascended_mask_of_the_bewitcher_blue', 
                      'Red Mask Of The Bewitcher': 'ascended_mask_of_the_bewitcher_red', 'Beige Mask Of Rorschach': 'ascended_mask_of_rorschach_beige', 'Grey Mask Of Rorschach': 'ascended_mask_of_rorschach_grey', 'Red Mask Of The Scarab': 'ascended_mask_of_the_scarab_red', 'Grey Mask Of The Scarab': 'ascended_mask_of_the_scarab_grey', 'Blue Mask Of Wisdom': 'ascended_mask_of_wisdom_blue', 'Red Mask Of Wisdom': 'ascended_mask_of_wisdom_red', 'Red Mask Of The Shadows': 'ascended_mask_of_the_shadows_red', 
                      'White Mask Of The Shadows': 'ascended_mask_of_the_shadows_white', 'Grey Mask Of The Silence': 'ascended_mask_of_the_silence_grey', 'Red Mask Of The Silence': 'ascended_mask_of_the_silence_red', 'Grey Mask Of The Merciful': 'ascended_mask_of_the_merciful_grey', 'Red Mask Of The Merciful': 'ascended_mask_of_the_merciful_red', 'Grey Mask Of The Banned': 'ascended_mask_of_the_banned_grey', 'Blue Mask Of The Banned': 'ascended_mask_of_the_banned_blue', 'Grey Mask Of The Speaking Wind': 'ascended_mask_of_the_speaking_wind_grey', 
                      'Red Mask Of The Speaking Wind': 'ascended_mask_of_the_speaking_wind_red', 'Light Mask Of The Infinite Dusk': 'ascended_mask_of_the_infinite_dusk_light', 'Dark Mask Of The Infinite Dusk': 'ascended_mask_of_the_infinite_dusk_dark', 'Blue Mask Of The Kooky': 'ascended_mask_of_the_kooky_blue', 'Red Mask Of The Kooky': 'ascended_mask_of_the_kooky_red', 'Red Mask Of The Moon': 'ascended_mask_of_the_moon_red', 'Blue Mask Of The Moon': 'ascended_mask_of_the_moon_blue', 'Black Mask Of The Deer': 'ascended_mask_of_the_deer_black', 
                      'White Mask Of The Deer': 'ascended_mask_of_the_deer_white', 'Blue Mask Of The Deep Valley': 'ascended_mask_of_the_deep_valley_blue', 'Red Mask Of The Deep Valley': 'ascended_mask_of_the_deep_valley_red', 'Blue Mask Of The Wanderer': 'ascended_mask_of_the_wanderer_blue', 'Red Mask Of The Wanderer': 'ascended_mask_of_the_wanderer_red', 'White Mask Of The Rising Sun': 'ascended_mask_of_the_rising_sun_white', 'Blue Mask Of The Rising Sun': 'ascended_mask_of_the_rising_sun_blue', 'Blue Mask Of The Reacher': 'ascended_mask_of_the_reacher_blue', 
                      'Beige Mask Of The Reacher': 'ascended_mask_of_the_reacher_beige', 'Black Mask Of The Rufa': 'ascended_mask_of_the_rufa_black', 'Red Mask Of The Rufa': 'ascended_mask_of_the_rufa_red', 'Yellow Mask Of The Dreamer': 'ascended_mask_of_the_dreamer_yellow', 'Red Mask Of The Dreamer': 'ascended_mask_of_the_dreamer_red', 'White Mask Of Death': 'ascended_mask_of_death_white', 'Grey Mask Of Death': 'ascended_mask_of_death_grey', 'Blue Mask Of The Trinity': 'ascended_mask_of_the_trinity_blue', 'Red Mask Of The Trinity': 'ascended_mask_of_the_trinity_red', 
                      'Red Mask Of The Discordant': 'ascended_mask_of_the__discordant_red', 'Grey Mask Of The Discordant': 'ascended_mask_of_the__discordant_grey', 'Blue Mask Of The Hunter': 'ascended_mask_of_the_hunter_blue', 'Red Mask Of The Hunter': 'ascended_mask_of_the_hunter_red', 'Black Mask Of The Seeker': 'ascended_mask_of_the_seeker_black', 'Red Mask Of The Seeker': 'ascended_mask_of_the_seeker_red', 'Black Mask Of The Underworld': 'ascended_mask_of_the_underworld_black', 'Grey Mask Of The Underworld': 'ascended_mask_of_the_underworld_grey', 
                      'Blue Mask Of The Fox': 'ascended_mask_of_the_fox_blue', 'Red Mask Of The Fox': 'ascended_mask_of_the_fox_red', 'Blue Mask Of The Dunes': 'ascended_mask_of_the_dunes_blue', 'Beige Mask Of The Dunes': 'ascended_mask_of_the_dunes_beige'}
                  
            },
        'BONDED MASK':
            {'BASE': {'Bonded Mask': 'ascended_bonded_mask_base'},
            
             'STRAPS': {'Shackle Straps': 'ascended_bonded_mask_shackle_straps', 'Twine Straps': 'ascended_bonded_mask_twine_straps', 'Knotted Straps': 'ascended_bonded_mask_knotted_straps', 'Pearls Straps': 'ascended_bonded_mask_pearls_straps'},
             
             'EARS': {'Hooks': 'ascended_bonded_mask_ears_hooks', 'Rounded Ears': 'ascended_bonded_mask_ears_rounded_ears', 'Tufts': 'ascended_bonded_mask_ears_tufts', 'Pierced Ears': 'ascended_bonded_mask_ears_pierced', 'Grips': 'ascended_bonded_mask_ears_grips'},

             'MOUTH': {'Beige Awing Mouth': 'ascended_bonded_mask_awing_mouth_beige', 'Red Awing Mouth': 'ascended_bonded_mask_awing_mouth_red', 'Scraping Mouth': 'ascended_bonded_mask_scraping_mouth', 'Ant Mouth': 'ascended_bonded_mask_ant_mouth', 
                       'Monkey Mouth': 'ascended_bonded_mask_monkey_mouth', 'Grey Trinity Mouth': 'ascended_bonded_mask_trinity_mouth_grey', 'Red Trinity Mouth': 'ascended_bonded_mask_trinity_mouth_red', 'Beige Stern Mouth': 'ascended_bonded_mask_stern_mouth_beige', 
                       'Red Stern Mouth': 'ascended_bonded_mask_stern_mouth_red', 'Loop Mouth': 'ascended_bonded_mask_loop_mouth', 'Beige Doubtful Mouth': 'ascended_bonded_mask_doubtful_mouth_beige', 'Red Doubtful Mouth': 'ascended_bonded_mask_doubtful_mouth_red', 'Unreal Mouth': 'ascended_bonded_mask_unreal_mouth'},
             
             'EYES': {'Round Eyes': 'ascended_bonded_mask_eyes_round', 'layered visor': 'ascended_bonded_mask_eyes_layered', 'abstract eyes': 'ascended_bonded_mask_eyes_abstract', 'Gazing visor': 'ascended_bonded_mask_eyes_gazing_visor', 'Flat Visor': 'ascended_bonded_mask_eyes_flat_visor', 
                      'crossed visor': 'ascended_bonded_mask_eyes_crossed_visor', 'focused eye': 'ascended_bonded_mask_eyes_focused', 'superior sign': 'ascended_bonded_mask_eyes_superior_sign', 'narrow eyes': 'ascended_bonded_mask_eyes_narrow', 'rimmed visor': 'ascended_bonded_mask_eyes_rimmed_visor', 
                      'converging sign': 'ascended_bonded_mask_eyes_converging_sign', 'awkward eyes': 'ascended_bonded_mask_eyes_awkward'},
             
             'TOP': {'beige feathers': 'ascended_bonded_mask_top_feathers_beige', 'dark feathers': 'ascended_bonded_mask_top_feathers_dark', 'Four Rods': 'ascended_bonded_mask_top_four_rods', 'layered brow': 'ascended_bonded_mask_top_layered_brow', 'beige hooks': 'ascended_bonded_mask_top_hooks_beige', 
                     'dark hooks': 'ascended_bonded_mask_top_hooks_dark', 'superior fur': 'ascended_bonded_mask_top_superior_fur', 'red buns': 'ascended_bonded_mask_top_red_buns', 'beige horns and tusks': 'ascended_bonded_mask_top_horns_and_tusks_beige', 'Dark horns and tusks': 'ascended_bonded_mask_top_horns_and_tusks_dark', 
                     'stoic tail': 'ascended_bonded_mask_top_stoic_tail', 'Dark lunar ornament': 'ascended_bonded_mask_top_lunar_ornament_dark', 'light lunar ornament': 'ascended_bonded_mask_top_lunar_ornament_light', 'bullish horns': 'ascended_bonded_mask_top_bullish_horns'}

            }
            
        }
